# 스프링 부트 2.4 이전에는 default 영역으로 인식되었지만,
# 스프링 부트 2.4 부터는 제일 마지막 정의된 내용으로 덮어씌워진다.

spring:
  config.activate.on-profile: daemon-local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: kyo
    password: 1q2w3e4r

daemon:
  nick-name: Developer local
  root-uri: "http://local.com:8080"


---
spring:
  config.activate.on-profile: daemon-dev
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: kyo
    password: 1q2w3e4r

daemon:
  nick-name: Developer dev
  root-uri: "http://dev.com"
